apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: cnrm-system/cnrm-controller-manager-packagename
  name: cnrm-controller-manager-packagename
  namespace: cnrm-system
  annotations:
    config.kubernetes.io/local-config: generated
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|cnrm-system|cnrm-controller-manager-packagename'
  ownerReferences:
  - apiVersion: core.cnrm.cloud.google.com/v1beta1
    kind: ConfigConnectorContext
    name: configconnectorcontext.core.cnrm.cloud.google.com
    namespace: dev