apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  name: root
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/deletion-policy: "abandon"
spec:
  displayName: "root"
  folderRef:
    external: example-folder
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  name: environments
  namespace: config-control
spec:
  displayName: environments
  folderRef:
    name: root